//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScenarioEditor.rc
//
#define ID_SEPARATOR                    0
#define VS_VERSION_INFO                 1
#define IDR_MAINFRAME                   100
#define AFX_IDC_LISTBOX                 100
#define IDR_MAIN_MENU                   101
#define AFX_IDC_CHANGE                  101
#define IDR_MAIN_TOOLBAR                102
#define AFX_IDC_BROWSER                 102
#define IDR_MAIN_ACCEL                  103
#define IDD_SCENARIO_EDITOR_DIALOG      200
#define IDD_SCENARIO_SETUP_PAGE         201
#define AFX_IDC_PRINT_DOCNAME           201
#define IDD_ASSET_ENTITY_EDITOR_PAGE    202
#define AFX_IDC_PRINT_PRINTERNAME       202
#define IDD_MOTION_PATH_EDITOR_PAGE     203
#define AFX_IDC_PRINT_PORTNAME          203
#define IDD_OUTPUT_PLAYBACK_PAGE        204
#define AFX_IDC_PRINT_PAGENUM           204
#define IDD_PREVIEW_PAGE                205
#define IDD_CATALOG_EDITOR              210
#define IDD_CATALOG_ADD                 211
#define IDD_PROMPT_NAME                 212
#define IDS_APP_TITLE                   300
#define IDS_STATE_IDLE                  301
#define IDS_TIME_DEFAULT                302
#define IDS_PROGRESS_DEFAULT            303
#define IDS_ERRORS_DEFAULT              304
#define IDS_WARNINGS_DEFAULT            305
#define IDS_INFO_DEFAULT                306
#define IDS_PDUS_DEFAULT                307
#define IDS_BW_DEFAULT                  308
#define IDC_MAIN_TABCTRL                1000
#define AFX_IDC_FONTPROP                1000
#define AFX_IDC_FONTNAMES               1001
#define AFX_IDC_FONTSTYLES              1002
#define AFX_IDC_FONTSIZES               1003
#define AFX_IDC_STRIKEOUT               1004
#define AFX_IDC_UNDERLINE               1005
#define AFX_IDC_SAMPLEBOX               1006
#define IDC_EDIT_SCENARIO_NAME          1100
#define AFX_IDC_COLOR_BLACK             1100
#define IDC_EDIT_SCENARIO_DESCRIPTION   1101
#define AFX_IDC_COLOR_WHITE             1101
#define IDC_RADIO_DIS_V6                1102
#define AFX_IDC_COLOR_RED               1102
#define IDC_RADIO_DIS_V7                1103
#define AFX_IDC_COLOR_GREEN             1103
#define IDC_EDIT_EXERCISE_ID            1104
#define AFX_IDC_COLOR_BLUE              1104
#define IDC_EDIT_SITE_ID                1105
#define AFX_IDC_COLOR_YELLOW            1105
#define IDC_EDIT_APPLICATION_ID         1106
#define AFX_IDC_COLOR_MAGENTA           1106
#define IDC_DATETIME_SCENARIO_START     1107
#define AFX_IDC_COLOR_CYAN              1107
#define IDC_EDIT_DURATION_SECONDS       1108
#define AFX_IDC_COLOR_GRAY              1108
#define IDC_EDIT_DEFAULT_UPDATE_RATE    1109
#define AFX_IDC_COLOR_LIGHTGRAY         1109
#define IDC_COMBO_DEFAULT_COORD_MODE    1110
#define AFX_IDC_COLOR_DARKRED           1110
#define IDC_EDIT_ORIGIN_LAT             1111
#define AFX_IDC_COLOR_DARKGREEN         1111
#define IDC_EDIT_ORIGIN_LON             1112
#define AFX_IDC_COLOR_DARKBLUE          1112
#define IDC_EDIT_ORIGIN_ALT             1113
#define AFX_IDC_COLOR_LIGHTBROWN        1113
#define IDC_BTN_USE_ENTITY_AS_ORIGIN    1114
#define AFX_IDC_COLOR_DARKMAGENTA       1114
#define IDC_BTN_CLEAR_ORIGIN            1115
#define AFX_IDC_COLOR_DARKCYAN          1115
#define IDC_CHK_VALIDATE_BEFORE_SEND    1116
#define AFX_IDC_COLORPROP               1116
#define IDC_CHK_VALIDATE_BEFORE_RECORD  1117
#define AFX_IDC_SYSTEMCOLORS            1117
#define IDC_CHK_VALIDATE_BEFORE_REPLAY  1118
#define IDC_TREE_ASSETS                 1200
#define IDC_BTN_ADD_ASSET               1201
#define AFX_IDC_PROPNAME                1201
#define IDC_BTN_DELETE_ASSET            1202
#define AFX_IDC_PICTURE                 1202
#define IDC_BTN_DUPLICATE_ASSET         1203
#define AFX_IDC_BROWSE                  1203
#define IDC_BTN_MOVE_ASSET              1204
#define AFX_IDC_CLEAR                   1204
#define IDC_BTN_VALIDATE_ASSET          1205
#define IDC_CHK_ENTITY_ENABLED          1206
#define IDC_EDIT_ENTITY_NAME            1207
#define IDC_EDIT_ENTITY_DESCRIPTION     1208
#define IDC_EDIT_ENTITY_MARKING         1209
#define IDC_COMBO_ENTITY_FORCE_ID       1210
#define IDC_COMBO_ENTITY_KIND           1211
#define IDC_COMBO_ENTITY_DOMAIN         1212
#define IDC_COMBO_ENTITY_COUNTRY        1213
#define IDC_COMBO_ENTITY_CATEGORY       1214
#define IDC_COMBO_ENTITY_SUBCATEGORY    1215
#define IDC_EDIT_ENTITY_SPECIFIC        1216
#define IDC_EDIT_ENTITY_EXTRA           1217
#define IDC_EDIT_ENTITY_SITE_ID         1218
#define IDC_EDIT_ENTITY_APP_ID          1219
#define IDC_EDIT_ENTITY_ID              1220
#define IDC_COMBO_ENTITY_COORD_MODE     1221
#define IDC_EDIT_ENTITY_LAT             1222
#define IDC_EDIT_ENTITY_LON             1223
#define IDC_EDIT_ENTITY_ALT             1224
// LEGACY: removed from IDD_ASSET_ENTITY_EDITOR_PAGE in the Initial-State
// single-row refactor. The IDC_EDIT_ENTITY_LAT/LON/ALT controls are now
// polymorphic and hold whichever frame matches IDC_COMBO_ENTITY_COORD_MODE.
// IDs retained for reference / external test tooling that may still grep
// for them.
#define IDC_EDIT_ENTITY_LOCAL_X         1225
#define IDC_EDIT_ENTITY_LOCAL_Y         1226
#define IDC_EDIT_ENTITY_LOCAL_Z         1227
#define IDC_EDIT_ENTITY_ECEF_X          1228
#define IDC_EDIT_ENTITY_ECEF_Y          1229
#define IDC_EDIT_ENTITY_ECEF_Z          1230
#define IDC_EDIT_ENTITY_HEADING         1231
#define IDC_EDIT_ENTITY_PITCH           1232
#define IDC_EDIT_ENTITY_ROLL            1233
#define IDC_EDIT_ENTITY_INITIAL_SPEED   1234
#define IDC_EDIT_ENTITY_BEGIN_TIME      1235
#define IDC_EDIT_ENTITY_END_TIME        1236
#define IDC_EDIT_ENTITY_UPDATE_RATE     1237
#define IDC_COMBO_MOTION_ENTITY         1300
#define IDC_LIST_MOTION_SEGMENTS        1301
#define IDC_BTN_ADD_SEGMENT             1302
#define IDC_BTN_DELETE_SEGMENT          1303
#define IDC_BTN_DUPLICATE_SEGMENT       1304
#define IDC_BTN_SEGMENT_MOVE_UP         1305
#define IDC_BTN_SEGMENT_MOVE_DOWN       1306
#define IDC_BTN_VALIDATE_SEGMENT        1307
#define IDC_CHK_SEGMENT_ENABLED         1308
#define IDC_EDIT_SEGMENT_START_TIME     1309
#define IDC_EDIT_SEGMENT_END_TIME       1310
#define IDC_COMBO_MOTION_TYPE           1311
#define IDC_COMBO_SEGMENT_COORD_MODE    1312
#define IDC_EDIT_SEGMENT_DESCRIPTION    1313
#define IDC_STATIC_MOTION_PLACEHOLDER   1314
#define IDC_LIST_WAYPOINTS              1315
#define IDC_BTN_IMPORT_CSV              1316
#define IDC_BTN_EXPORT_CSV              1317
#define IDC_RADIO_MODE_UDP_UNICAST      1400
#define IDC_RADIO_MODE_UDP_MULTICAST    1401
#define IDC_RADIO_MODE_TCP              1402
#define IDC_RADIO_MODE_FILE_RECORDING   1403
#define IDC_RADIO_MODE_PREVIEW_ONLY     1404
#define IDC_STATIC_GROUP_UDP_UNICAST    1405
#define IDC_STATIC_GROUP_UDP_MULTICAST  1406
#define IDC_STATIC_GROUP_TCP            1407
#define IDC_STATIC_GROUP_FILE_RECORD    1408
#define IDC_STATIC_GROUP_FILE_REPLAY    1409
#define IDC_STATIC_GROUP_PLAYBACK       1410
#define IDC_BTN_PLAYBACK_START          1411
#define IDC_BTN_PLAYBACK_PAUSE          1412
#define IDC_BTN_PLAYBACK_RESUME         1413
#define IDC_BTN_PLAYBACK_STOP           1414
#define IDC_CHK_PLAYBACK_LOOP           1415
#define IDC_COMBO_PLAYBACK_SPEED        1416
#define IDC_EDIT_UDP_UNICAST_IP         1417
#define IDC_EDIT_UDP_UNICAST_PORT       1418
#define IDC_EDIT_UDP_MULTICAST_GROUP    1419
#define IDC_EDIT_UDP_MULTICAST_PORT     1420
#define IDC_EDIT_UDP_MULTICAST_TTL      1421
#define IDC_EDIT_UDP_MULTICAST_IFACE    1422
#define IDC_CHK_UDP_MULTICAST_LOOP      1423
#define IDC_EDIT_RECORDING_PATH         1424
#define IDC_BTN_RECORDING_BROWSE        1425
#define IDC_EDIT_REPLAY_PATH            1426
#define IDC_BTN_REPLAY_BROWSE           1427
#define IDC_STATIC_PREVIEW_CANVAS       1500
#define IDC_BTN_PREVIEW_START           1501
#define IDC_BTN_PREVIEW_PAUSE           1502
#define IDC_BTN_PREVIEW_RESUME          1503
#define IDC_BTN_PREVIEW_STOP            1504
#define IDC_SLIDER_PREVIEW_TIME         1505
#define IDC_BTN_PREVIEW_ZOOM_IN         1506
#define IDC_BTN_PREVIEW_ZOOM_OUT        1507
#define IDC_BTN_PREVIEW_FIT             1508
#define IDC_CHK_PREVIEW_LABELS          1509
#define IDC_CHK_PREVIEW_TRAILS          1510
#define IDC_CHK_PREVIEW_PATHS           1511
#define IDC_CHK_PREVIEW_ORIENTATION     1512

// Motion Path Editor — Ellipse fields (two-foci + length + speed +
// start-bearing form).
#define IDC_GROUP_ELLIPSE_PARAMS        1530
#define IDC_LBL_F1                      1531
#define IDC_LBL_F2                      1532
#define IDC_LBL_LEN                     1533
#define IDC_LBL_BRG                     1534
#define IDC_LBL_SPD                     1535
#define IDC_LBL_DIR                     1536
#define IDC_EDIT_F1_A                   1540
#define IDC_EDIT_F1_B                   1541
#define IDC_EDIT_F1_C                   1542
#define IDC_EDIT_F2_A                   1543
#define IDC_EDIT_F2_B                   1544
#define IDC_EDIT_F2_C                   1545
#define IDC_EDIT_LEN                    1546
#define IDC_EDIT_BEARING                1547
#define IDC_EDIT_SPEED                  1548
#define IDC_COMBO_DIR                   1549

// Asset/Entity Editor — single dynamic label for the position triple.
// The text switches between "Lat / Lon / Alt:" / "Local X / Y / Z (m):"
// / "ECEF X / Y / Z:" based on the Initial Coord Mode combo.
#define IDC_LBL_ENTITY_POSITION         1550

// Scenario Setup — physical model defaults (Phase 1).
#define IDC_GROUP_PHYSMODEL             1560
#define IDC_RADIO_PHYS_IGNORE           1561
#define IDC_RADIO_PHYS_VALIDATE         1562
#define IDC_RADIO_PHYS_LIMIT            1563
#define IDC_CHK_SPEED_MULT              1564
#define IDC_EDIT_SPEED_MULT             1565

// Asset/Entity Editor — per-entity physical model override (Phase 1).
#define IDC_GROUP_PHYSMODEL_ENTITY      1570
#define IDC_RADIO_PHYS_INHERIT          1571
#define IDC_RADIO_PHYS_E_IGNORE         1572
#define IDC_RADIO_PHYS_E_VALIDATE       1573
#define IDC_RADIO_PHYS_E_LIMIT          1574
#define IDC_CHK_E_SPEED_MULT            1575
#define IDC_EDIT_E_SPEED_MULT           1576

// Motion Path Editor — Line / Stationary / StopHold subfields.
// Visible when the segment Type is Line (both Start and End rows) or
// Stationary / StopHold (Start row only). Labels relabel based on the
// segment's CoordMode, same pattern as the Ellipse Center fields.
#define IDC_GROUP_LINE_PARAMS           1580
#define IDC_LBL_LINE_START_POS          1581
#define IDC_EDIT_LINE_START_A           1582
#define IDC_EDIT_LINE_START_B           1583
#define IDC_EDIT_LINE_START_C           1584
#define IDC_EDIT_LINE_START_H           1585
#define IDC_EDIT_LINE_START_P           1586
#define IDC_EDIT_LINE_START_R           1587
#define IDC_LBL_LINE_END_POS            1588
#define IDC_EDIT_LINE_END_A             1589
#define IDC_EDIT_LINE_END_B             1590
#define IDC_EDIT_LINE_END_C             1591
#define IDC_EDIT_LINE_END_H             1592
#define IDC_EDIT_LINE_END_P             1593
#define IDC_EDIT_LINE_END_R             1594

// Per-type group static-label IDs (so SetTypeSpecificVisibility can hide
// them when the corresponding group isn't active). Plain IDC_STATIC
// labels share id -1 and can't be addressed individually.
#define IDC_LBL_ELLIPSE_HINT            1617
#define IDC_LBL_LINE_START_H_TAG        1620
#define IDC_LBL_LINE_START_P_TAG        1621
#define IDC_LBL_LINE_START_R_TAG        1622
#define IDC_LBL_LINE_END_H_TAG          1623
#define IDC_LBL_LINE_END_P_TAG          1624
#define IDC_LBL_LINE_END_R_TAG          1625
#define IDC_LBL_LINE_HINT               1626
#define IDC_LBL_LINE_SPEED              1627
#define IDC_EDIT_LINE_SPEED             1628

// Catalog Editor (IDD_CATALOG_EDITOR) — wireframe pass IDs.
#define IDC_BTN_EDIT_CATALOG            1800
#define IDC_TREE_CATALOG                1801
#define IDC_LBL_CATALOG_SELECTION       1802
#define IDC_LBL_CATALOG_ID              1803
#define IDC_EDIT_CATALOG_ID             1804
#define IDC_LBL_CATALOG_NAME            1805
#define IDC_EDIT_CATALOG_NAME           1806
#define IDC_LBL_CATALOG_TYPE            1807
// Unified Add (1810) replaces the per-type buttons. 1811..1814 retired.
#define IDC_BTN_ADD_NODE                1810
#define IDC_BTN_DELETE_NODE             1815
#define IDC_BTN_SAVE_CATALOG            1816
#define IDC_BTN_SAVE_CLOSE_CATALOG      1817
// Attributes grid + buttons (replaces the 24 fixed envelope edits).
#define IDC_LIST_ATTRIBUTES             1820
#define IDC_BTN_ADD_ATTRIBUTE           1821
#define IDC_BTN_DELETE_ATTRIBUTE        1822
#define IDC_LBL_CATALOG_HINT            1823

// Secondary "Add Catalog Node" dialog (IDD_CATALOG_ADD).
#define IDC_COMBO_ADD_TYPE              1860
#define IDC_LBL_ADD_ID                  1861
#define IDC_EDIT_ADD_ID                 1862
#define IDC_LBL_ADD_NAME                1863
#define IDC_EDIT_ADD_NAME               1864
#define IDC_LBL_ADD_BREADCRUMB          1865
#define IDC_LBL_PROMPT                  1866
#define IDC_EDIT_PROMPT                 1867

#define AFX_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define AFX_IDD_NEWTYPEDLG              30721
#define AFX_IDD_PRINTDLG                30722
#define AFX_IDD_PREVIEW_TOOLBAR         30723
#define AFX_IDD_INSERTOBJECT            30724
#define AFX_IDD_CHANGEICON              30725
#define AFX_IDD_CONVERT                 30726
#define AFX_IDD_PASTESPECIAL            30727
#define AFX_IDD_EDITLINKS               30728
#define AFX_IDD_FILEBROWSE              30729
#define AFX_IDD_BUSY                    30730
#define AFX_IDD_OBJECTPROPERTIES        30732
#define AFX_IDD_CHANGESOURCE            30733
#define AFX_IDD_EMPTYDIALOG             30734
#define AFX_IDC_CONTEXTHELP             30977
#define AFX_IDC_MAGNIFY                 30978
#define AFX_IDC_SMALLARROWS             30979
#define AFX_IDC_HSPLITBAR               30980
#define AFX_IDC_VSPLITBAR               30981
#define AFX_IDC_NODROPCRSR              30982
#define AFX_IDC_TRACKNWSE               30983
#define AFX_IDC_TRACKNESW               30984
#define AFX_IDC_TRACKNS                 30985
#define AFX_IDC_TRACKWE                 30986
#define AFX_IDC_TRACK4WAY               30987
#define AFX_IDC_MOVE4WAY                30988
#define AFX_IDB_MINIFRAME_MENU          30994
#define AFX_IDB_CHECKLISTBOX_95         30996
#define AFX_IDR_PREVIEW_ACCEL           30997
#define AFX_IDC_MOUSE_PAN_NW            30998
#define AFX_IDC_MOUSE_PAN_N             30999
#define AFX_IDC_MOUSE_PAN_NE            31000
#define AFX_IDC_MOUSE_PAN_W             31001
#define AFX_IDC_MOUSE_PAN_HV            31002
#define AFX_IDC_MOUSE_PAN_E             31003
#define AFX_IDC_MOUSE_PAN_SW            31004
#define AFX_IDC_MOUSE_PAN_S             31005
#define AFX_IDC_MOUSE_PAN_SE            31006
#define AFX_IDC_MOUSE_PAN_HORZ          31007
#define AFX_IDC_MOUSE_PAN_VERT          31008
#define AFX_IDC_MOUSE_ORG_HORZ          31009
#define AFX_IDC_MOUSE_ORG_VERT          31010
#define AFX_IDC_MOUSE_ORG_HV            31011
#define AFX_IDC_MOUSE_MASK              31012
#define AFX_IDI_STD_MDIFRAME            31233
#define AFX_IDI_STD_FRAME               31234
#define ID_FILE_NEW_SCENARIO            32000
#define ID_FILE_OPEN_SCENARIO           32001
#define ID_FILE_SAVE_SCENARIO           32002
#define ID_FILE_SAVE_SCENARIO_AS        32003
#define ID_FILE_OPEN_RECORDING          32004
#define ID_SCENARIO_VALIDATE            32010
#define ID_SCENARIO_GENERATE_RECORDING  32011
#define ID_SCENARIO_PREVIEW             32012
#define ID_SCENARIO_RESET_CLOCK         32013
#define ID_PLAYBACK_START               32020
#define ID_PLAYBACK_PAUSE               32021
#define ID_PLAYBACK_RESUME              32022
#define ID_PLAYBACK_STOP                32023
#define ID_PLAYBACK_LOOP                32024
#define ID_PLAYBACK_SPEED_025           32025
#define ID_PLAYBACK_SPEED_050           32026
#define ID_PLAYBACK_SPEED_1             32027
#define ID_PLAYBACK_SPEED_2             32028
#define ID_PLAYBACK_SPEED_10            32029
#define ID_NETWORK_OPEN_OUTPUT          32040
#define ID_NETWORK_CLOSE_OUTPUT         32041
#define ID_NETWORK_TEST_UDP             32042
#define ID_NETWORK_TEST_MULTICAST       32043
#define ID_NETWORK_TEST_TCP             32044
#define ID_VIEW_VALIDATION_PANEL        32050
#define ID_HELP_ABOUT                   32060
#define ID_HELP_PROTOCOL_NOTES          32061
#define ID_HELP_FILE_FORMAT_NOTES       32062
#define ID_TOOLS_RECORD                 32070
#define ID_TOOLS_REPLAY_FILE            32071
#define ID_TOOLS_SEND_LIVE              32072
#define ID_TB_LOOP_HOST                 32073
#define ID_TB_SPEED_HOST                32074
#define ID_TB_HELP_TOGGLE               32075
#define ID_KB_ADD_ASSET                 32080
#define ID_KB_DELETE_ASSET              32081
#define ID_KB_DUPLICATE_ASSET           32082
#define ID_KB_MOVE_ASSET                32083
#define ID_KB_ADD_SEGMENT               32084
#define ID_KB_DELETE_SEGMENT            32085
#define ID_KB_DUPLICATE_SEGMENT         32086
#define AFX_IDD_PROPPAGE_COLOR          32257
#define AFX_IDD_PROPPAGE_FONT           32258
#define AFX_IDD_PROPPAGE_PICTURE        32259
#define ID_INDICATOR_STATE              33000
#define ID_INDICATOR_TIME               33001
#define ID_INDICATOR_PROGRESS           33002
#define ID_INDICATOR_ERRORS             33003
#define ID_INDICATOR_WARNINGS           33004
#define ID_INDICATOR_INFO               33005
#define ID_INDICATOR_PDUS               33006
#define ID_INDICATOR_BW                 33007
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define AFX_IDS_HELPMODEMESSAGE         0xE002
#define AFX_IDS_APP_TITLE_EMBEDDING     0xE003
#define AFX_IDS_COMPANY_NAME            0xE004
#define AFX_IDS_OBJ_TITLE_INPLACE       0xE005
#define AFX_IDS_APP_ID                  0xE006
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_NEW_FRAME               0xE10D
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_FORMAT_FONT                  0xE160
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define ID_OLE_VERB_POPUP               0xE220
#define AFX_ID_PREVIEW_CLOSE            0xE300
#define AFX_ID_PREVIEW_NUMPAGE          0xE301
#define AFX_ID_PREVIEW_NEXT             0xE302
#define AFX_ID_PREVIEW_PREV             0xE303
#define AFX_ID_PREVIEW_PRINT            0xE304
#define AFX_ID_PREVIEW_ZOOMIN           0xE305
#define AFX_ID_PREVIEW_ZOOMOUT          0xE306
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_INDICATOR_KANA               0xE706
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REBAR                   0xE804
#define ID_VIEW_AUTOARRANGE             0xE805
#define ID_VIEW_SMALLICON               0xE810
#define ID_VIEW_LARGEICON               0xE811
#define ID_VIEW_LIST                    0xE812
#define ID_VIEW_DETAILS                 0xE813
#define ID_VIEW_LINEUP                  0xE814
#define ID_VIEW_BYNAME                  0xE815
#define ID_RECORD_FIRST                 0xE900
#define ID_RECORD_LAST                  0xE901
#define ID_RECORD_NEXT                  0xE902
#define ID_RECORD_PREV                  0xE903
#define AFX_TIMER_ID_FIRST              0xEC00
#define AFX_TIMER_ID_DISPLAY_AHWND_EVENT 0xEC00
#define AFX_TIMER_ID_AUTO_HIDE_SLIDE_IN_EVENT 0xEC01
#define AFX_TIMER_ID_AUTO_HIDE_SLIDE_OUT_EVENT 0xEC02
#define AFX_TIMER_ID_CHECK_AUTO_HIDE_CONDITION 0xEC03
#define AFX_TIMER_ID_DOCK_EVENT         0xEC04
#define AFX_TIMER_ID_CHECK_ROLL_STATE   0xEC05
#define AFX_TIMER_ID_VISIBILITY_TIMER   0xEC06
#define AFX_TIMER_ID_ACCELERATOR_NOTIFY_EVENT 0xEC07
#define AFX_TIMER_ID_TIMER_TRACKING     0xEC08
#define AFX_TIMER_ID_TIMER_WAIT         0xEC09
#define AFX_TIMER_ID_TIMER_CHECK        0xEC0A
#define AFX_TIMER_ID_TASK_ANIMATION     0xEC0B
#define AFX_TIMER_ID_TASK_SCROLL        0xEC0C
#define AFX_TIMER_ID_AUTOCOMMAND        0xEC0D
#define AFX_TIMER_ID_ALERT_CLOSE_POPUP  0xEC0E
#define AFX_TIMER_ID_ALERT_ANIMATION    0xEC0F
#define AFX_TIMER_ID_ALERT_CHECK_ACTIVITY 0xEC10
#define AFX_TIMER_ID_TB_SHOW_DROPDOWN   0xEC11
#define AFX_TIMER_ID_MENU_SHOW_ALL_ITEMS 0xEC12
#define AFX_TIMER_ID_OUTLOOK_BAR_SCRL_UP 0xEC13
#define AFX_TIMER_ID_OUTLOOK_BAR_SCRL_DN 0xEC14
#define AFX_TIMER_ID_MENU_POPUP_ANIMATION 0xEC15
#define AFX_TIMER_ID_MENU_POPUP_SCROLL  0xEC16
#define AFX_TIMER_ID_MENUBAR_POPUP      0xEC17
#define AFX_TIMER_ID_MENUBAR_REMOVE     0xEC18
#define AFX_TIMER_ID_RIBBONBAR_AUTO_COMMAND 0xEC19
#define AFX_TIMER_ID_RIBBONBAR_SHOW_KEYTIPS 0xEC1A
#define AFX_TIMER_ID_RIBBONPANEL_POPUP  0xEC1B
#define AFX_TIMER_ID_RIBBONPANEL_REMOVE 0xEC1C
#define AFX_TIMER_ID_RIBBONPANEL_AUTO_COMMAND 0xEC1D
#define AFX_TIMER_ID_LAST               0xEC1F
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_MDICHILD                0xEF1F
#define AFX_IDS_DESKACCESSORY           0xEFDA
#define AFX_IDS_OPENFILE                0xF000
#define AFX_IDS_SAVEFILE                0xF001
#define AFX_IDS_ALLFILTER               0xF002
#define AFX_IDS_UNTITLED                0xF003
#define AFX_IDS_SAVEFILECOPY            0xF004
#define AFX_IDS_PREVIEW_CLOSE           0xF005
#define AFX_IDS_UNNAMED_FILE            0xF006
#define AFX_IDS_HIDE                    0xF011
#define AFX_IDP_NO_ERROR_AVAILABLE      0xF020
#define AFX_IDS_NOT_SUPPORTED_EXCEPTION 0xF021
#define AFX_IDS_RESOURCE_EXCEPTION      0xF022
#define AFX_IDS_MEMORY_EXCEPTION        0xF023
#define AFX_IDS_USER_EXCEPTION          0xF024
#define AFX_IDS_INVALID_ARG_EXCEPTION   0xF025
#define AFX_IDS_PRINTONPORT             0xF040
#define AFX_IDS_ONEPAGE                 0xF041
#define AFX_IDS_TWOPAGE                 0xF042
#define AFX_IDS_PRINTPAGENUM            0xF043
#define AFX_IDS_PREVIEWPAGEDESC         0xF044
#define AFX_IDS_PRINTDEFAULTEXT         0xF045
#define AFX_IDS_PRINTDEFAULT            0xF046
#define AFX_IDS_PRINTFILTER             0xF047
#define AFX_IDS_PRINTCAPTION            0xF048
#define AFX_IDS_PRINTTOFILE             0xF049
#define AFX_IDS_OBJECT_MENUITEM         0xF080
#define AFX_IDS_EDIT_VERB               0xF081
#define AFX_IDS_ACTIVATE_VERB           0xF082
#define AFX_IDS_CHANGE_LINK             0xF083
#define AFX_IDS_AUTO                    0xF084
#define AFX_IDS_MANUAL                  0xF085
#define AFX_IDS_FROZEN                  0xF086
#define AFX_IDS_ALL_FILES               0xF087
#define AFX_IDS_SAVE_MENU               0xF088
#define AFX_IDS_UPDATE_MENU             0xF089
#define AFX_IDS_SAVE_AS_MENU            0xF08A
#define AFX_IDS_SAVE_COPY_AS_MENU       0xF08B
#define AFX_IDS_EXIT_MENU               0xF08C
#define AFX_IDS_UPDATING_ITEMS          0xF08D
#define AFX_IDS_METAFILE_FORMAT         0xF08E
#define AFX_IDS_DIB_FORMAT              0xF08F
#define AFX_IDS_BITMAP_FORMAT           0xF090
#define AFX_IDS_LINKSOURCE_FORMAT       0xF091
#define AFX_IDS_EMBED_FORMAT            0xF092
#define AFX_IDS_PASTELINKEDTYPE         0xF094
#define AFX_IDS_UNKNOWNTYPE             0xF095
#define AFX_IDS_RTF_FORMAT              0xF096
#define AFX_IDS_TEXT_FORMAT             0xF097
#define AFX_IDS_INVALID_CURRENCY        0xF098
#define AFX_IDS_INVALID_DATETIME        0xF099
#define AFX_IDS_INVALID_DATETIMESPAN    0xF09A
#define AFX_IDP_INVALID_FILENAME        0xF100
#define AFX_IDP_FAILED_TO_OPEN_DOC      0xF101
#define AFX_IDP_FAILED_TO_SAVE_DOC      0xF102
#define AFX_IDP_ASK_TO_SAVE             0xF103
#define AFX_IDP_FAILED_TO_CREATE_DOC    0xF104
#define AFX_IDP_FILE_TOO_LARGE          0xF105
#define AFX_IDP_FAILED_TO_START_PRINT   0xF106
#define AFX_IDP_FAILED_TO_LAUNCH_HELP   0xF107
#define AFX_IDP_INTERNAL_FAILURE        0xF108
#define AFX_IDP_COMMAND_FAILURE         0xF109
#define AFX_IDP_FAILED_MEMORY_ALLOC     0xF10A
#define AFX_IDP_UNREG_DONE              0xF10B
#define AFX_IDP_UNREG_FAILURE           0xF10C
#define AFX_IDP_DLL_LOAD_FAILED         0xF10D
#define AFX_IDP_DLL_BAD_VERSION         0xF10E
#define AFX_IDP_PARSE_INT               0xF110
#define AFX_IDP_PARSE_REAL              0xF111
#define AFX_IDP_PARSE_INT_RANGE         0xF112
#define AFX_IDP_PARSE_REAL_RANGE        0xF113
#define AFX_IDP_PARSE_STRING_SIZE       0xF114
#define AFX_IDP_PARSE_RADIO_BUTTON      0xF115
#define AFX_IDP_PARSE_BYTE              0xF116
#define AFX_IDP_PARSE_UINT              0xF117
#define AFX_IDP_PARSE_DATETIME          0xF118
#define AFX_IDP_PARSE_CURRENCY          0xF119
#define AFX_IDP_PARSE_GUID              0xF11A
#define AFX_IDP_PARSE_TIME              0xF11B
#define AFX_IDP_PARSE_DATE              0xF11C
#define AFX_IDP_FAILED_INVALID_FORMAT   0xF120
#define AFX_IDP_FAILED_INVALID_PATH     0xF121
#define AFX_IDP_FAILED_DISK_FULL        0xF122
#define AFX_IDP_FAILED_ACCESS_READ      0xF123
#define AFX_IDP_FAILED_ACCESS_WRITE     0xF124
#define AFX_IDP_FAILED_IO_ERROR_READ    0xF125
#define AFX_IDP_FAILED_IO_ERROR_WRITE   0xF126
#define AFX_IDP_SCRIPT_ERROR            0xF130
#define AFX_IDP_SCRIPT_DISPATCH_EXCEPTION 0xF131
#define AFX_IDP_STATIC_OBJECT           0xF180
#define AFX_IDP_FAILED_TO_CONNECT       0xF181
#define AFX_IDP_SERVER_BUSY             0xF182
#define AFX_IDP_BAD_VERB                0xF183
#define AFX_IDS_NOT_DOCOBJECT           0xF184
#define AFX_IDP_FAILED_TO_NOTIFY        0xF185
#define AFX_IDP_FAILED_TO_LAUNCH        0xF186
#define AFX_IDP_ASK_TO_UPDATE           0xF187
#define AFX_IDP_FAILED_TO_UPDATE        0xF188
#define AFX_IDP_FAILED_TO_REGISTER      0xF189
#define AFX_IDP_FAILED_TO_AUTO_REGISTER 0xF18A
#define AFX_IDP_FAILED_TO_CONVERT       0xF18B
#define AFX_IDP_GET_NOT_SUPPORTED       0xF18C
#define AFX_IDP_SET_NOT_SUPPORTED       0xF18D
#define AFX_IDP_ASK_TO_DISCARD          0xF18E
#define AFX_IDP_FAILED_TO_CREATE        0xF18F
#define AFX_IDP_FAILED_MAPI_LOAD        0xF190
#define AFX_IDP_INVALID_MAPI_DLL        0xF191
#define AFX_IDP_FAILED_MAPI_SEND        0xF192
#define AFX_IDP_FILE_NONE               0xF1A0
#define AFX_IDP_FILE_GENERIC            0xF1A1
#define AFX_IDP_FILE_NOT_FOUND          0xF1A2
#define AFX_IDP_FILE_BAD_PATH           0xF1A3
#define AFX_IDP_FILE_TOO_MANY_OPEN      0xF1A4
#define AFX_IDP_FILE_ACCESS_DENIED      0xF1A5
#define AFX_IDP_FILE_INVALID_FILE       0xF1A6
#define AFX_IDP_FILE_REMOVE_CURRENT     0xF1A7
#define AFX_IDP_FILE_DIR_FULL           0xF1A8
#define AFX_IDP_FILE_BAD_SEEK           0xF1A9
#define AFX_IDP_FILE_HARD_IO            0xF1AA
#define AFX_IDP_FILE_SHARING            0xF1AB
#define AFX_IDP_FILE_LOCKING            0xF1AC
#define AFX_IDP_FILE_DISKFULL           0xF1AD
#define AFX_IDP_FILE_EOF                0xF1AE
#define AFX_IDP_ARCH_NONE               0xF1B0
#define AFX_IDP_ARCH_GENERIC            0xF1B1
#define AFX_IDP_ARCH_READONLY           0xF1B2
#define AFX_IDP_ARCH_ENDOFFILE          0xF1B3
#define AFX_IDP_ARCH_WRITEONLY          0xF1B4
#define AFX_IDP_ARCH_BADINDEX           0xF1B5
#define AFX_IDP_ARCH_BADCLASS           0xF1B6
#define AFX_IDP_ARCH_BADSCHEMA          0xF1B7
#define AFX_IDS_OCC_SCALEUNITS_PIXELS   0xF1C0
#define AFX_IDS_STATUS_FONT             0xF230
#define AFX_IDS_TOOLTIP_FONT            0xF231
#define AFX_IDS_UNICODE_FONT            0xF232
#define AFX_IDS_MINI_FONT               0xF233
#define AFX_IDP_SQL_CONNECT_FAIL        0xF281
#define AFX_IDP_SQL_RECORDSET_FORWARD_ONLY 0xF282
#define AFX_IDP_SQL_EMPTY_COLUMN_LIST   0xF283
#define AFX_IDP_SQL_FIELD_SCHEMA_MISMATCH 0xF284
#define AFX_IDP_SQL_ILLEGAL_MODE        0xF285
#define AFX_IDP_SQL_MULTIPLE_ROWS_AFFECTED 0xF286
#define AFX_IDP_SQL_NO_CURRENT_RECORD   0xF287
#define AFX_IDP_SQL_NO_ROWS_AFFECTED    0xF288
#define AFX_IDP_SQL_RECORDSET_READONLY  0xF289
#define AFX_IDP_SQL_SQL_NO_TOTAL        0xF28A
#define AFX_IDP_SQL_ODBC_LOAD_FAILED    0xF28B
#define AFX_IDP_SQL_DYNASET_NOT_SUPPORTED 0xF28C
#define AFX_IDP_SQL_SNAPSHOT_NOT_SUPPORTED 0xF28D
#define AFX_IDP_SQL_API_CONFORMANCE     0xF28E
#define AFX_IDP_SQL_SQL_CONFORMANCE     0xF28F
#define AFX_IDP_SQL_NO_DATA_FOUND       0xF290
#define AFX_IDP_SQL_ROW_UPDATE_NOT_SUPPORTED 0xF291
#define AFX_IDP_SQL_ODBC_V2_REQUIRED    0xF292
#define AFX_IDP_SQL_NO_POSITIONED_UPDATES 0xF293
#define AFX_IDP_SQL_LOCK_MODE_NOT_SUPPORTED 0xF294
#define AFX_IDP_SQL_DATA_TRUNCATED      0xF295
#define AFX_IDP_SQL_ROW_FETCH           0xF296
#define AFX_IDP_SQL_INCORRECT_ODBC      0xF297
#define AFX_IDP_SQL_UPDATE_DELETE_FAILED 0xF298
#define AFX_IDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED 0xF299
#define AFX_IDP_SQL_FIELD_NOT_FOUND     0xF29A
#define AFX_IDP_SQL_BOOKMARKS_NOT_SUPPORTED 0xF29B
#define AFX_IDP_SQL_BOOKMARKS_NOT_ENABLED 0xF29C
#define AFX_IDS_DELETED                 0xF29D
#define AFX_IDP_DAO_ENGINE_INITIALIZATION 0xF2B0
#define AFX_IDP_DAO_DFX_BIND            0xF2B1
#define AFX_IDP_DAO_OBJECT_NOT_OPEN     0xF2B2
#define AFX_IDP_DAO_ROWTOOSHORT         0xF2B3
#define AFX_IDP_DAO_BADBINDINFO         0xF2B4
#define AFX_IDP_DAO_COLUMNUNAVAILABLE   0xF2B5
#define AFX_IDS_HTTP_TITLE              0xF2D1
#define AFX_IDS_HTTP_NO_TEXT            0xF2D2
#define AFX_IDS_HTTP_BAD_REQUEST        0xF2D3
#define AFX_IDS_HTTP_AUTH_REQUIRED      0xF2D4
#define AFX_IDS_HTTP_FORBIDDEN          0xF2D5
#define AFX_IDS_HTTP_NOT_FOUND          0xF2D6
#define AFX_IDS_HTTP_SERVER_ERROR       0xF2D7
#define AFX_IDS_HTTP_NOT_IMPLEMENTED    0xF2D8
#define AFX_IDS_CHECKLISTBOX_UNCHECK    0xF2E1
#define AFX_IDS_CHECKLISTBOX_CHECK      0xF2E2
#define AFX_IDS_CHECKLISTBOX_MIXED      0xF2E3
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_1 0xF2E4
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_2 0xF2E5
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_3 0xF2E6
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_4 0xF2E7
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_5 0xF2E8
#define AFX_IDS_AUTOSAVE_RECOVERY_ASK_6 0xF2E9
#define AFX_IDS_AUTOSAVE_RECOVERED      0xF2EA
#define AFX_IDS_PROPPAGE_UNKNOWN        0xFE01
#define AFX_IDS_COLOR_DESKTOP           0xFE04
#define AFX_IDS_COLOR_APPWORKSPACE      0xFE05
#define AFX_IDS_COLOR_WNDBACKGND        0xFE06
#define AFX_IDS_COLOR_WNDTEXT           0xFE07
#define AFX_IDS_COLOR_MENUBAR           0xFE08
#define AFX_IDS_COLOR_MENUTEXT          0xFE09
#define AFX_IDS_COLOR_ACTIVEBAR         0xFE0A
#define AFX_IDS_COLOR_INACTIVEBAR       0xFE0B
#define AFX_IDS_COLOR_ACTIVETEXT        0xFE0C
#define AFX_IDS_COLOR_INACTIVETEXT      0xFE0D
#define AFX_IDS_COLOR_ACTIVEBORDER      0xFE0E
#define AFX_IDS_COLOR_INACTIVEBORDER    0xFE0F
#define AFX_IDS_COLOR_WNDFRAME          0xFE10
#define AFX_IDS_COLOR_SCROLLBARS        0xFE11
#define AFX_IDS_COLOR_BTNFACE           0xFE12
#define AFX_IDS_COLOR_BTNSHADOW         0xFE13
#define AFX_IDS_COLOR_BTNTEXT           0xFE14
#define AFX_IDS_COLOR_BTNHIGHLIGHT      0xFE15
#define AFX_IDS_COLOR_DISABLEDTEXT      0xFE16
#define AFX_IDS_COLOR_HIGHLIGHT         0xFE17
#define AFX_IDS_COLOR_HIGHLIGHTTEXT     0xFE18
#define AFX_IDS_REGULAR                 0xFE19
#define AFX_IDS_BOLD                    0xFE1A
#define AFX_IDS_ITALIC                  0xFE1B
#define AFX_IDS_BOLDITALIC              0xFE1C
#define AFX_IDS_SAMPLETEXT              0xFE1D
#define AFX_IDS_DISPLAYSTRING_FONT      0xFE1E
#define AFX_IDS_DISPLAYSTRING_COLOR     0xFE1F
#define AFX_IDS_DISPLAYSTRING_PICTURE   0xFE20
#define AFX_IDS_PICTUREFILTER           0xFE21
#define AFX_IDS_PICTYPE_UNKNOWN         0xFE22
#define AFX_IDS_PICTYPE_NONE            0xFE23
#define AFX_IDS_PICTYPE_BITMAP          0xFE24
#define AFX_IDS_PICTYPE_METAFILE        0xFE25
#define AFX_IDS_PICTYPE_ICON            0xFE26
#define AFX_IDS_COLOR_PPG               0xFE28
#define AFX_IDS_COLOR_PPG_CAPTION       0xFE29
#define AFX_IDS_FONT_PPG                0xFE2A
#define AFX_IDS_FONT_PPG_CAPTION        0xFE2B
#define AFX_IDS_PICTURE_PPG             0xFE2C
#define AFX_IDS_PICTURE_PPG_CAPTION     0xFE2D
#define AFX_IDS_PICTUREBROWSETITLE      0xFE30
#define AFX_IDS_BORDERSTYLE_0           0xFE31
#define AFX_IDS_BORDERSTYLE_1           0xFE32
#define AFX_IDS_VERB_EDIT               0xFE40
#define AFX_IDS_VERB_PROPERTIES         0xFE41
#define AFX_IDP_PICTURECANTOPEN         0xFE83
#define AFX_IDP_PICTURECANTLOAD         0xFE84
#define AFX_IDP_PICTURETOOLARGE         0xFE85
#define AFX_IDP_PICTUREREADFAILED       0xFE86
#define AFX_IDP_E_ILLEGALFUNCTIONCALL   0xFEA0
#define AFX_IDP_E_OVERFLOW              0xFEA1
#define AFX_IDP_E_OUTOFMEMORY           0xFEA2
#define AFX_IDP_E_DIVISIONBYZERO        0xFEA3
#define AFX_IDP_E_OUTOFSTRINGSPACE      0xFEA4
#define AFX_IDP_E_OUTOFSTACKSPACE       0xFEA5
#define AFX_IDP_E_BADFILENAMEORNUMBER   0xFEA6
#define AFX_IDP_E_FILENOTFOUND          0xFEA7
#define AFX_IDP_E_BADFILEMODE           0xFEA8
#define AFX_IDP_E_FILEALREADYOPEN       0xFEA9
#define AFX_IDP_E_DEVICEIOERROR         0xFEAA
#define AFX_IDP_E_FILEALREADYEXISTS     0xFEAB
#define AFX_IDP_E_BADRECORDLENGTH       0xFEAC
#define AFX_IDP_E_DISKFULL              0xFEAD
#define AFX_IDP_E_BADRECORDNUMBER       0xFEAE
#define AFX_IDP_E_BADFILENAME           0xFEAF
#define AFX_IDP_E_TOOMANYFILES          0xFEB0
#define AFX_IDP_E_DEVICEUNAVAILABLE     0xFEB1
#define AFX_IDP_E_PERMISSIONDENIED      0xFEB2
#define AFX_IDP_E_DISKNOTREADY          0xFEB3
#define AFX_IDP_E_PATHFILEACCESSERROR   0xFEB4
#define AFX_IDP_E_PATHNOTFOUND          0xFEB5
#define AFX_IDP_E_INVALIDPATTERNSTRING  0xFEB6
#define AFX_IDP_E_INVALIDUSEOFNULL      0xFEB7
#define AFX_IDP_E_INVALIDFILEFORMAT     0xFEB8
#define AFX_IDP_E_INVALIDPROPERTYVALUE  0xFEB9
#define AFX_IDP_E_INVALIDPROPERTYARRAYINDEX 0xFEBA
#define AFX_IDP_E_SETNOTSUPPORTEDATRUNTIME 0xFEBB
#define AFX_IDP_E_SETNOTSUPPORTED       0xFEBC
#define AFX_IDP_E_NEEDPROPERTYARRAYINDEX 0xFEBD
#define AFX_IDP_E_SETNOTPERMITTED       0xFEBE
#define AFX_IDP_E_GETNOTSUPPORTEDATRUNTIME 0xFEBF
#define AFX_IDP_E_GETNOTSUPPORTED       0xFEC0
#define AFX_IDP_E_PROPERTYNOTFOUND      0xFEC1
#define AFX_IDP_E_INVALIDCLIPBOARDFORMAT 0xFEC2
#define AFX_IDP_E_INVALIDPICTURE        0xFEC3
#define AFX_IDP_E_PRINTERERROR          0xFEC4
#define AFX_IDP_E_CANTSAVEFILETOTEMP    0xFEC5
#define AFX_IDP_E_SEARCHTEXTNOTFOUND    0xFEC6
#define AFX_IDP_E_REPLACEMENTSTOOLONG   0xFEC7
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32100
#define _APS_NEXT_CONTROL_VALUE         1601
#define _APS_NEXT_SYMED_VALUE           34000
#endif
#endif
